# @author Shelton Ngwenya, R00203947

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guess_that_phrase.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17guess_that_phrase.proto\"#\n\x11UserChoiceRequest\x12\x0e\n\x06letter\x18\x01 \x01(\t\"%\n\x12UserChoiceResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2S\n\x14\x44isplayGuessedLetter\x12;\n\x0eSendUserChoice\x12\x12.UserChoiceRequest\x1a\x13.UserChoiceResponse\"\x00\x42;\n io.grpc.examples.guessthatphraseB\x0fGuessThatPhraseP\x01\xa2\x02\x03GTPb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guess_that_phrase_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n io.grpc.examples.guessthatphraseB\017GuessThatPhraseP\001\242\002\003GTP'
  _USERCHOICEREQUEST._serialized_start=27
  _USERCHOICEREQUEST._serialized_end=62
  _USERCHOICERESPONSE._serialized_start=64
  _USERCHOICERESPONSE._serialized_end=101
  _DISPLAYGUESSEDLETTER._serialized_start=103
  _DISPLAYGUESSEDLETTER._serialized_end=186
# @@protoc_insertion_point(module_scope)
