# @author Shelton Ngwenya, R00203947

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import guess_that_phrase_pb2 as guess__that__phrase__pb2


class DisplayGuessedLetterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendUserChoice = channel.unary_unary(
                '/DisplayGuessedLetter/SendUserChoice',
                request_serializer=guess__that__phrase__pb2.UserChoiceRequest.SerializeToString,
                response_deserializer=guess__that__phrase__pb2.UserChoiceResponse.FromString,
                )


class DisplayGuessedLetterServicer(object):
    """The greeting service definition.
    """

    def SendUserChoice(self, request, context):
        """Sends a Phrase
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DisplayGuessedLetterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendUserChoice': grpc.unary_unary_rpc_method_handler(
                    servicer.SendUserChoice,
                    request_deserializer=guess__that__phrase__pb2.UserChoiceRequest.FromString,
                    response_serializer=guess__that__phrase__pb2.UserChoiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DisplayGuessedLetter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DisplayGuessedLetter(object):
    """The greeting service definition.
    """

    @staticmethod
    def SendUserChoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DisplayGuessedLetter/SendUserChoice',
            guess__that__phrase__pb2.UserChoiceRequest.SerializeToString,
            guess__that__phrase__pb2.UserChoiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
