# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guess_that_phrase.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17guess_that_phrase.proto\"\x1f\n\rLetterRequest\x12\x0e\n\x06letter\x18\x01 \x01(\t\"!\n\x0eLetterResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\rPhraseRequest\x12\x0e\n\x06phrase\x18\x01 \x01(\t\"!\n\x0ePhraseResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2x\n\x14\x44isplayGuessedLetter\x12/\n\nSendLetter\x12\x0e.LetterRequest\x1a\x0f.LetterResponse\"\x00\x12/\n\nSendPhrase\x12\x0e.PhraseRequest\x1a\x0f.PhraseResponse\"\x00\x42;\n io.grpc.examples.guessthatphraseB\x0fGuessThatPhraseP\x01\xa2\x02\x03GTPb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guess_that_phrase_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n io.grpc.examples.guessthatphraseB\017GuessThatPhraseP\001\242\002\003GTP'
  _LETTERREQUEST._serialized_start=27
  _LETTERREQUEST._serialized_end=58
  _LETTERRESPONSE._serialized_start=60
  _LETTERRESPONSE._serialized_end=93
  _PHRASEREQUEST._serialized_start=95
  _PHRASEREQUEST._serialized_end=126
  _PHRASERESPONSE._serialized_start=128
  _PHRASERESPONSE._serialized_end=161
  _DISPLAYGUESSEDLETTER._serialized_start=163
  _DISPLAYGUESSEDLETTER._serialized_end=283
# @@protoc_insertion_point(module_scope)
